server:
  port: 8081
mybatis:
  mapper-locations: classpath:mapperxml/*Mapper.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    drive-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33066/springcloud?serverTimezone=GMT%2B8
    username: root
    password: 123456
  security:
    user:
      name: admin
      password: 123456
  redis:
    host: 106.13.125.253
    port: 6379
logging:
  level:
    com.aust.mapper: debug


